name: Build and Deploy Products

on:
  push:
    branches: [ main ]
    paths:
      - 'data/products.csv'
      - 'Imagenes_de_productos/**'
      - 'src/app/productos/**'
      - 'src/components/product-*.tsx'
      - 'src/lib/csv-parser.ts'
      - 'src/types/product.ts'
  workflow_dispatch:
    inputs:
      force_rebuild:
        description: 'Forzar reconstrucción completa'
        required: false
        default: false
        type: boolean

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: npm ci

      - name: Validate CSV structure
        run: |
          echo "Validando estructura del CSV..."
          if [ ! -f "data/products.csv" ]; then
            echo "❌ Error: No se encuentra el archivo data/products.csv"
            exit 1
          fi
          
          # Verificar encabezados requeridos
          headers=$(head -n 1 data/products.csv)
          required_headers="nombre;slug;categoria;descripcion_corta;caracteristicas;precio;moneda;imagenes;estado;cta_whatsapp"
          
          if [[ "$headers" != "$required_headers" ]]; then
            echo "❌ Error: Los encabezados del CSV no coinciden con la estructura requerida"
            echo "Encabezados encontrados: $headers"
            echo "Encabezados requeridos: $required_headers"
            exit 1
          fi
          
          echo "✅ Estructura del CSV válida"

      - name: Validate images existence
        run: |
          echo "Validando existencia de imágenes..."
          
          # Leer el CSV y verificar que las imágenes existan
          while IFS=';' read -r nombre slug categoria descripcion_corta caracteristicas precio moneda imagenes estado cta_whatsapp; do
            # Saltar encabezado
            if [[ "$nombre" == "nombre" ]]; then
              continue
            fi
            
            # Solo procesar productos visibles
            if [[ "$estado" != "visible" ]]; then
              continue
            fi
            
            # Verificar imagen principal
            IFS=',' read -ra IMAGE_ARRAY <<< "$imagenes"
            main_image="${IMAGE_ARRAY[0]}"
            
            if [[ ! -f "$main_image" ]]; then
              echo "⚠️ Advertencia: No se encuentra la imagen principal $main_image para el producto $nombre"
            else
              echo "✅ Imagen encontrada: $main_image"
            fi
            
          done < data/products.csv
          
          echo "✅ Validación de imágenes completada"

      - name: Build static site
        run: npm run build:static

      - name: Validate build output
        run: |
          echo "Validando salida del build..."
          
          # Verificar que se generaron las páginas de productos
          if [ ! -f "out/productos/index.html" ]; then
            echo "❌ Error: No se generó la página de listado de productos"
            exit 1
          fi
          
          # Verificar que se generaron las páginas de detalle
          product_count=$(grep -c "visible" data/products.csv)
          if [[ $product_count -gt 0 ]]; then
            echo "✅ Página de listado generada correctamente"
          else
            echo "⚠️ No hay productos visibles en el CSV"
          fi
          
          echo "✅ Validación del build completada"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  notify:
    runs-on: ubuntu-latest
    needs: [build, deploy]
    if: always()
    steps:
      - name: Notify build status
        run: |
          if [[ "${{ needs.build.result }}" == "success" && "${{ needs.deploy.result }}" == "success" ]]; then
            echo "✅ Build y deploy completados exitosamente"
            echo "🌐 Sitio disponible en: https://jpc19832020-tech.github.io/EXOstudioV/"
          else
            echo "❌ Error en el build o deploy"
            echo "Build result: ${{ needs.build.result }}"
            echo "Deploy result: ${{ needs.deploy.result }}"
            exit 1
          fi